SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS bn_distribution;
DROP TABLE IF EXISTS bn_don;
DROP TABLE IF EXISTS bn_besoin;
DROP TABLE IF EXISTS bn_element;
DROP TABLE IF EXISTS bn_typeBesoin;
DROP TABLE IF EXISTS bn_ville;
DROP TABLE IF EXISTS bn_region;

SET FOREIGN_KEY_CHECKS = 1;
